apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: win-sql-vm-passthrough
  namespace: ocp-virt-vms
spec:
  parentRefs:
    - name: enterprise-gateway
      namespace: openshift-ingress
      sectionName: tls-passthrough
  hostnames:
    - "win-sql-01.vms.corp.local"
  rules:
    - backendRefs:
        - name: win-sql-01-vm-service
          port: 1433
          weight: 100
