// /etc/named.conf for OpenShift 4.20 Helper Node
options {
    listen-on port 53 { any; };
    listen-on-v6 port 53 { ::1; };
    directory   "/var/named";
    dump-file   "/var/named/data/cache_dump.db";
    statistics-file "/var/named/data/named_stats.txt";
    memstatistics-file "/var/named/data/named_mem_stats.txt";
    allow-query     { any; };
    recursion yes;
    forwarders {
        8.8.8.8;
        1.1.1.1;
    };
    dnssec-validation no;
};

zone "corp.local" IN {
    type master;
    file "zone.corp.local";
};

zone "10.168.192.in-addr.arpa" IN {
    type master;
    file "zone.192.168.10";
};
