apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: kubevirt-hyperconverged
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  featureGates:
    withHostPassthroughCPU: true
    alignCPUs: true
  liveMigrationConfig:
    bandwidthPerMigration: "1024Mi"
    completionTimeoutPerGiB: 800
    parallelMigrationsPerCluster: 10
    parallelOutboundMigrationsPerNode: 2
    progressTimeout: 150
  storageImportConfig:
    insecureRegistries: []
  workloadUpdateStrategy:
    workloadUpdateMethods:
      - LiveMigrate
    batchEvictionSize: 10
    batchEvictionInterval: "1m"
