apiVersion: v1
baseDomain: cloud.example.com
metadata:
  name: ocp-gcp-prod
publish: Internal
credentialsMode: Manual
controlPlane:
  name: master
  replicas: 3
  platform:
    gcp:
      type: n2-standard-8
      zones:
        - europe-west1-b
        - europe-west1-c
        - europe-west1-d
compute:
  - name: worker
    replicas: 3
    platform:
      gcp:
        type: n2-standard-16
networking:
  networkType: OVNKubernetes
platform:
  gcp:
    projectID: enterprise-cloud-host-prod
    region: europe-west1
    network: vpc-shared-prod
    controlPlaneSubnet: snet-ocp-masters
    computeSubnet: snet-ocp-workers
pullSecret: '{"auths":{"YOUR_PULL_SECRET_HERE":{"auth":"..."}}}'
sshKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... admin@example.com'
