apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: sailoperator.io/v1alpha1
kind: Istio
metadata:
  name: default
  namespace: istio-system
spec:
  version: v1.23.0
  namespace: istio-system
  values:
    profile: ambient
    pilot:
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 2Gi
      env:
        PILOT_ENABLE_AMBIENT: "true"
        PILOT_ENABLE_GATEWAY_API: "true"
        PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER: "true"
    meshConfig:
      accessLogFile: /dev/stdout
      enableAutoMtls: true
      defaultConfig:
        proxyMetadata:
          ISTIO_META_ENABLE_HBONE: "true"
      trustDomain: cluster.local
      extensionProviders:
        - name: prometheus
          prometheus: {}
