apiVersion: v1
baseDomain: example.com
metadata:
  name: ocp-standard
compute:
  - name: worker
    replicas: 3
    architecture: amd64
controlPlane:
  name: master
  replicas: 3
  architecture: amd64
networking:
  networkType: OVNKubernetes
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
  machineNetwork:
    - cidr: 192.168.10.0/24
platform:
  baremetal:
    apiVIPs:
      - 192.168.10.100
    ingressVIPs:
      - 192.168.10.101
pullSecret: '{"auths":{"YOUR_PULL_SECRET_HERE":{"auth":"..."}}}'
sshKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI... admin@example.com'
